### ISSUE TITLE
🏗 Prevent Supabase from pausing projects

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#949]
## Description

Supabase will put our project to sleep after 5-7 days of inactivity. This can happen somewhat often if the project is not actively being worked on. This issue is being created to try and address this problem.

## Acceptance

Create a GitHub action that pings our Supabase instance once a day. Ensure this prevents the project from being put to sleep.

## Example

```yml
name: Ping Supabase Request

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day

jobs:
  fetch-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run fetch request
        run: |
          curl -X POST 'https://rrwgpqzbprqhocvasbdp.supabase.co/auth/v1/token?grant_type=password' \
                    -H "apikey: xxx" \
                    -H "Content-Type: application/json" \
                    -d '{
                      "email": "github@no.mail",
                      "password": "xxx"
                    }'
```
